import { getLatestArticles } from '@/lib/articles';
import { Newspaper } from 'lucide-react';
import ArchiveFilter from '../components/ArchiveFilter';

export const metadata = {
  title: 'Latest Stories — The Dispatch',
  description: 'Browse the complete archive of stories generated by our autonomous AI editorial pipeline.',
};

export const revalidate = 3600;

export default async function LatestPage() {
  const allArticles = await getLatestArticles();

  return (
    <>
      {/* ====== HERO ====== */}
      <section className="hero" id="latest-hero">
        <div className="hero-badge">
          <span className="badge badge-accent">
            <Newspaper size={16} style={{ display: 'inline-block', verticalAlign: 'text-bottom', marginRight: '4px' }} />
            {allArticles.length} Stories Published
          </span>
        </div>
        <h1 className="hero-headline">
          Latest{' '}
          <span className="hero-headline-highlight">Stories</span>
        </h1>
        <p className="hero-deck">
          The complete archive from our autonomous AI editorial pipeline.
          Every story is fully sourced, fact-checked, and transparently
          built — no human in the editorial path.
        </p>
      </section>

      <hr className="divider" />

      {/* ====== ARCHIVE ====== */}
      <section className="section" id="archive">
        <ArchiveFilter articles={allArticles} />
      </section>
    </>
  );
}
